build: false
shallow_clone: true
platform: 'x86'
branches:
  only:
    - appveyor
# Inspired by https://github.com/Codeception/base/blob/master/appveyor.yml and https://github.com/phpmd/phpmd/blob/master/appveyor.yml
install:
  - SET PATH=C:\Program Files\MySql\MySQL Server 5.6\bin\;%PATH%
  - cinst -y curl
  - SET PATH=C:\Program Files\curl;%PATH%
  #which is only needed by the test suite.
  - cinst -y which
  - SET PATH=C:\Program Files\which;%PATH%
  - git clone -q https://github.com/acquia/DevDesktopCommon.git #For tar, cksum, ...
  - SET PATH=%APPVEYOR_BUILD_FOLDER%/DevDesktopCommon/bintools-win/msys/bin;%PATH%
  #Install PHP
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo variables_order="EGPCS" >> php.ini #Debugging related to https://github.com/drush-ops/drush/pull/646. May be unneeded.
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_pdo_pgsql.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - echo extension=php_pgsql.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  #Install Composer
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  #Install Drush's dependencies via Composer
  - php composer.phar -q install --prefer-dist -n --no-ansi
  - SET PATH=%APPVEYOR_BUILD_FOLDER%;%APPVEYOR_BUILD_FOLDER%/vendor/bin;%PATH%
  #Create a sandbox for testing.
  - mkdir c:\drush_temp

services:
  - mysql

test_script:
  #- mysql -uroot -pPassword12! -hlocalhost -e "create database YourDatabase;"
  #- mysql -uroot -pPassword12! -hlocalhost -e "SHOW DATABASES;"
  - php -r "$a = new PDO('mysql:YourDatabase;host=localhost', 'root', 'Password12!'); foreach($a->query('SHOW DATABASES;') as $row) print_r($row);"
  - phpunit -v --configuration tests %PHPUNIT_ARGS%

cache:
  - c:\drush_temp

# environment variables
environment:
  global:
      UNISH_NO_TIMEOUTS: y
      UNISH_DB_URL: "mysql://root:Password12!@localhost"
      UNISH_TMP: c:\drush_temp

  matrix:
  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --group=base

  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --group=commands

  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --group=pm

  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --group=quick-drupal

  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --exclude-group=base,make,commands,pm,quick-drupal

  - UNISH_DRUPAL_MAJOR_VERSION: 7
    PHPUNIT_ARGS: --group=make
