site_name: Drush docs
theme: readthedocs
repo_url: https://github.com/drush-ops/drush
include_search: true
pages:
- Home: index.md
- General:
  - Install: install.md
  - Usage: usage.md
  - Example files: examples.md
  - Cron: cron.md
  - Shell aliases: shellaliases.md
  - Shell scripts: shellscripts.md
  - Bastion: bastion.md
  - Exporting Drupal configuration: config-exporting.md
- Writing commands/generators:
  - Command Authoring: commands.md
  - Generator Authoring: generators.md
  - Bootstrap: bootstrap.md
#use_directory_urls: false

markdown_extensions:
    - toc:
        permalink: ÔÉÅ
    - admonition:
