name: drush
type: php
docroot: sut
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "87"
router_https_port: "444"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: ""
disable_settings_management: true
webimage_extra_packages:
  - bash-completion
  - asciinema
# https://ddev.readthedocs.io/en/latest/users/extend/database-types/
# When switching DBs, use ddev delete --omit-snapshot
#database:
#  type: postgres
#  version: 14
web_environment:
  - UNISH_DB_URL=mysql://root:root@db
#  - "UNISH_DB_URL=sqlite://:memory:"
#  - UNISH_DB_URL=pgsql://db:db@db:5432
  - DRUSH_OPTIONS_URI=$DDEV_PRIMARY_URL
  - EDITOR=nano
